name: Push-To-EC2

on:
  push:
    branches:
    - main
    
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

#      - name: SSH into EC2
#        run: |
#          pwd
#          ls -al
#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/FirstWebServer_Key.pem
 #         ls -al
          
#          ssh -v -i key.pem ubuntu@18.220.150.224
#          pwd
#          ls
 #       env:
 #         SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          
#      - name: Deploy to Server
#        run: ssh -v -i ${{ secrets.EC2_SSH_KEY }} ubuntu@18.220.150.224
#       run: ssh -v -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: "--rsync-path=sudo"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
            
      - name: Remote SSH Commands with SSH Key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          scripts: |
            cd ~/git_pitstop
            sudo mv */var/www/littleGame 

      
        
